# ワークフロー名
name: test_line_notify
# 実行タイミング
on:
 push:

# 実行内容
jobs:
  build:
    # Ubuntsuで実行
    runs-on: ubuntu-latest
    
    # 実行する処理＆コマンド
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: data.txt
      - name: Run script
        run: |
          # main.pyの実行
          python main.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: data.txt